version: '3.8'

services:
  # PostgreSQL test database that mimics Supabase
  test-db:
    container_name: sql-test-db
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5